### ISSUE TITLE
Error running example.py 

### ISSUE THREAD

**Issue by eqian99** [hegelai/prompttools#6]
### 🐛 Describe the bug

Ran into this error when running example.py 

```python 
ERROR:root:Authentication error. Skipping request.
ERROR:root:Authentication error. Skipping request.
WARNING:root:Can't find similar_to_expected in scores. Did you run `evaluate`?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/qianh1/Code/prompttools/examples/prompttests/example.py", line 43, in <module>
    prompttest.main()
  File "/Users/qianh1/Code/prompttools/prompttools/testing/prompttest.py", line 108, in main
    failures = sum([test() for test in TESTS_TO_RUN])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qianh1/Code/prompttools/prompttools/testing/prompttest.py", line 108, in <listcomp>
    failures = sum([test() for test in TESTS_TO_RUN])
                    ^^^^^^
  File "/Users/qianh1/Code/prompttools/prompttools/testing/prompttest.py", line 58, in runs_test
    return run_prompt_template_test(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qianh1/Code/prompttools/prompttools/testing/runner/prompt_template_runner.py", line 82, in run_prompt_template_test
    scored_template[prompt_template] < threshold
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by steventkrawczyk** [comment]
It looks like you're trying to run the example without setting your `OPENAI_API_KEY`, or setting `DEBUG=1`. I'll make the instructions and error handling more explicit.
